### PR TITLE
Update to be compatible with h5py version 3.0

### PR DESCRIPTION
**Pull request by greschd**
In the 3.0 version, h5py changed the default to creates a `bytes` objects from variable-length strings instead of `str`. To remain compatible with existing objects, we call `.decode('utf-8')` in the appropriate places.

This commit also adds a `bytes` special type.

After the n-th time of being broken by changes to `h5py`, now we pin it - at least to the major version.

### CODE REVIEW

**Comment by mskoenz** [comment]
Waiting for CI pipeline ^^

**Comment by greschd** [comment]
Aany minute (hour?) now

**Comment by mskoenz** [comment]
Would it make sense to call encode explicitly too or just rely on h5py to do this?

**Comment by mskoenz** [comment]
Encode/Decode usually come in pairs

**Comment by greschd** [comment]
Yeah h5py does it - kinda. I had a quick look at their changelog, and it just converts `str` to "variable length string datatype", and the default for converting that back to Python changed from `str` to `bytes`: https://docs.h5py.org/en/stable/whatsnew/3.0.html#breaking-changes-deprecations

We could do it explicitly I guess - but it's sorta far away from each other in the code anyway.

Another option (just found that now) would be using [`Dataset.asstr()`](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.asstr) to do the decoding on the HDF5 side.

**Comment by mskoenz** [comment]
Those CI Pipelines tho :P

**Comment by mskoenz** [comment]
I think its fine, you mainly need to decode for backwards comp. Can be merged next year when CI passes

**Comment by greschd** [comment]
Migrating to travis-ci.com seems to fix it ¯\\_(ツ)_/¯

**Comment by greschd** [comment]
@mskoenz question on versioning: should this become ``1.0.1`` or ``1.1.0``? The only new feature is support for `bytes`.

**Comment by mskoenz** [comment]
it is an implementation detail change, no?

**Comment by mskoenz** [comment]
So patch lvl, no new interface was added, right?

**Comment by greschd** [comment]
Support for the `bytes` datatype was added, but it's a really minor new interface. Published as `1.0.1`.

**Pull request merged**
